version: '3'
services:
  ms-animes:
    container_name: ms-animes
    image: solanoae/ms-animes
    restart: always
    depends_on:
      - postgres_so
    volumes:
      - ./environmentsVars/.animes-env.yml:/usr/src/app/.env.yml
  postgres_so:
    container_name: postgres_so
    image: postgres
    ports:
      - "4561:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bv{-jqW{&L23dMkJ5N
      POSTGRES_DB: db_animes
  nginx:
    image: nginx
    container_name: reverse-proxy_so
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    links:
      - ms-animes
